---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-otel-demo
  namespace: demo
  labels:
    app: eks-otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-otel-demo
  template:
    metadata:
      labels:
        app: eks-otel-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: demo-app
        image: 173961276139.dkr.ecr.us-west-2.amazonaws.com/eks-otel-demo:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "otel-collector-opentelemetry-collector.tracing.svc.cluster.local:4318"
        - name: OTEL_SERVICE_NAME
          value: "eks-otel-demo"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=eks-otel-demo,service.version=1.0.0"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: eks-otel-demo-service
  namespace: demo
  labels:
    app: eks-otel-demo
spec:
  selector:
    app: eks-otel-demo
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-otel-loadgen
  namespace: demo
  labels:
    app: eks-otel-loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-otel-loadgen
  template:
    metadata:
      labels:
        app: eks-otel-loadgen
    spec:
      containers:
      - name: loadgen
        image: 173961276139.dkr.ecr.us-west-2.amazonaws.com/eks-otel-demo:latest
        command: ["/app/loadgen"]
        args:
        - "--target=http://eks-otel-demo-service.demo.svc.cluster.local"
        - "--duration=0"
        - "--rate=2"
        - "--workers=2"
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "otel-collector-opentelemetry-collector.tracing.svc.cluster.local:4318"
        - name: OTEL_SERVICE_NAME
          value: "eks-otel-loadgen"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
