apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-otel-crud
  region: us-west-2
  version: "1.29"

availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]

vpc:
  cidr: 10.0.0.0/16
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

nodeGroups:
  - name: system-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    amiFamily: AmazonLinux2023
    privateNetworking: true
    ssh:
      allow: true
    iam:
      withAddonPolicies:
        ebs: true
        efs: true
        awsLoadBalancerController: true
        cloudWatch: true
        autoScaler: true

  - name: app-nodes
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    volumeSize: 20
    amiFamily: AmazonLinux2023
    privateNetworking: true
    labels:
      nodegroup-type: application
    taints:
      - key: app
        value: "true"
        effect: NoSchedule
    iam:
      withAddonPolicies:
        ebs: true
        efs: true
        awsLoadBalancerController: true
        cloudWatch: true
        autoScaler: true

addons:
  - name: vpc-cni
    version: latest
  - name: kube-proxy
    version: latest
  - name: coredns
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]

iam:
  withOIDC: true
  serviceRoleARN: ""
  serviceAccounts: []
